// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package userdb

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	Name      string
}
