version: '3'

dotenv: ['.env']

vars:
  DB_CONN: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable

tasks:
  infra:
    desc: Start local infra
    cmds:
      - docker compose up -d

  server:
    desc: Run the server locally
    cmds:
      - go run cmd/server/main.go

  consumer:
    desc: Run the consumer locally
    cmds:
      - go run cmd/consumer/main.go

  sqlgen:
    desc: Generate sqlc pkgs
    cmds:
      # sqlc does not suppoort yml anchors
      - yq eval 'explode(.) | del(.common_overrides)' sqlc.yaml > .sqlc.inline.yaml
      - sqlc generate -f .sqlc.inline.yaml

  migrate:
    desc: Applies DB schema from sql
    deps:
      - task: sqlgen
        silent: true
      - task: infra
        silent: true
    cmds:
      - atlas schema apply --env default --url "{{.DB_CONN}}"

  test-unit:
    desc: Run unit tests
    cmds:
      - go test ./... {{.CLI_ARGS}}

  test-integration:
    desc: Run integration tests
    deps:
      - task: infra
        silent: true
    cmds:
      - go test --tags integration -p 1 ./... {{.CLI_ARGS}}
