version: '3'

dotenv: ['.env']

vars:
  DB_CONN: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable

tasks:
  install:
    cmds:
      - go mod tidy

  infra:
    desc: Start local infra
    cmds:
      - docker compose up -d

  run-api:
    desc: Run the api locally
    cmds:
      - go run cmd/api/main.go

  run-consumer:
    desc: Run the consumer locally
    cmds:
      - go run cmd/consumer/main.go

  run:
    deps:
      - run-api
      - run-consumer
    parallel: true


  sqlgen:
    desc: Generate sqlc pkgs
    cmds:
      # sqlc does not support yml anchors
      - yq eval 'explode(.) | del(.common_overrides)' sqlc.yaml > .sqlc.inline.yaml
      - sqlc generate -f .sqlc.inline.yaml

  migrate:
    desc: Applies DB schema from sql
    deps:
      - task: sqlgen
        silent: true
      - task: infra
        silent: true
    cmds:
      - atlas schema apply --env default --url "{{.DB_CONN}}"

  test-unit:
    desc: Run unit tests
    cmds:
      - go test --tags unit ./... {{.CLI_ARGS}}

  test-integration:
    desc: Run integration tests
    deps:
      - task: infra
        silent: true
    cmds:
      - go test --tags integration -p 1 ./... {{.CLI_ARGS}}
