// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package outboxdb

import (
	"time"

	"github.com/google/uuid"
)

type EventOutbox struct {
	ID           int32
	AggregateID  uuid.UUID
	EventContext []byte
	EventType    string
	Payload      []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Retries      int32
	ProcessedAt  *time.Time
}
