// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID        uuid.UUID
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	Status    string
}

type OrderItem struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Name      string
	Quantity  int32
	UnitPrice int64
}
