// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const listOrders = `-- name: ListOrders :many
SELECT id, version, created_at, updated_at, status, total
FROM orders
WHERE ($1::uuid IS NULL OR id > $1)
  AND ($2::text IS NULL OR status = $2)
ORDER BY id
LIMIT $3
`

type ListOrdersParams struct {
	After        *uuid.UUID
	Status       *string
	LimitPlusOne int32
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.After, arg.Status, arg.LimitPlusOne)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
