// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: repository.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, version, status, total)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateOrderParams struct {
	ID      uuid.UUID
	Version int32
	Status  string
	Total   int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Version,
		arg.Status,
		arg.Total,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, version, created_at, updated_at, status, total FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Total,
	)
	return i, err
}

const removeOrder = `-- name: RemoveOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) RemoveOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeOrder, id)
	return err
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET version = version + 1, updated_at = NOW(), status = $3, total = $4
WHERE id = $1
AND version = $2
RETURNING id
`

type UpdateOrderParams struct {
	ID      uuid.UUID
	Version int32
	Status  string
	Total   int64
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.Version,
		arg.Status,
		arg.Total,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
