// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
