// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const listUsers = `-- name: ListUsers :many
SELECT id, version, created_at, updated_at, name
FROM users
WHERE ($1::uuid IS NULL OR id > $1)
  AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
ORDER BY id
LIMIT $3
`

type ListUsersParams struct {
	After        *uuid.UUID
	Name         *string
	LimitPlusOne int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.After, arg.Name, arg.LimitPlusOne)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
