// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: repository.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, version, name)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	ID      uuid.UUID
	Version int32
	Name    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Version, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT id, version, created_at, updated_at, name FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const removeUser = `-- name: RemoveUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) RemoveUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET version = version + 1, updated_at = NOW(), name = $3
WHERE id = $1
AND version = $2
RETURNING id
`

type UpdateUserParams struct {
	ID      uuid.UUID
	Version int32
	Name    string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Version, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
