// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID          uuid.UUID
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	PublishDate time.Time
	Author      string
}
