// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sql

import (
	"context"

	"github.com/google/uuid"
)

const listPosts = `-- name: ListPosts :many
SELECT id, version, created_at, updated_at, title, publish_date, author
FROM posts
WHERE ($1::uuid IS NULL OR id > $1)
  AND ($2::text IS NULL OR title ILIKE '%' || $2 || '%')
ORDER BY id
LIMIT $3
`

type ListPostsParams struct {
	After        *uuid.UUID
	Title        *string
	LimitPlusOne int32
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.After, arg.Title, arg.LimitPlusOne)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.PublishDate,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
