// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: repository.sql

package sql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, version, created_at, updated_at, title, publish_date, author)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreatePostParams struct {
	ID          uuid.UUID
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	PublishDate time.Time
	Author      string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.PublishDate,
		arg.Author,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPost = `-- name: GetPost :one
SELECT id, version, created_at, updated_at, title, publish_date, author FROM posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.PublishDate,
		&i.Author,
	)
	return i, err
}

const removePost = `-- name: RemovePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) RemovePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removePost, id)
	return err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET version = version + 1, updated_at = $3, title = $4
WHERE id = $1
AND version = $2
RETURNING id
`

type UpdatePostParams struct {
	ID        uuid.UUID
	Version   int32
	UpdatedAt time.Time
	Title     string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Version,
		arg.UpdatedAt,
		arg.Title,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
